# -*- coding: utf-8 -*-
"""Face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Va79wJj0Ov3f9ETLNPZyzJuDgLgWh6XO
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Face_Detection
!unrar x "train.rar" "/content/drive/MyDrive/Face_Detection/"

# Commented out IPython magic to ensure Python compatibility.
#version yolov8
# %cd /content
!gdown --id 1dL0niKPx3ylM9qVfvRiTFb4vcsfyQ_0T
!gdown --id 1AMy69iovOLiTUwyi40PNUn1riyl7HWTP
!gdown --id 1Kn9_EBWI7Vyo-xg4ijc83xqruYgDqOyD

!pip install ultralytics

# Commented out IPython magic to ensure Python compatibility.
# Create training yaml file
# %cd /content
!rm mydataset.yaml # nếu có file thì xóa
!echo 'train: /content/drive/MyDrive/Face_Detection/train/images' >> mydataset.yaml
!echo 'val: /content/drive/MyDrive/Face_Detection/train/images' >> mydataset.yaml
!echo 'nc: 2' >> mydataset.yaml
!echo "names: ['Hai','Thu']" >> mydataset.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!yolo task=detect mode=train model=yolov8n.pt data=mydataset.yaml epochs=250 imgsz=640 batch=16

from ultralytics import YOLO
#Load file weights
path_weights = "/content/drive/MyDrive/Face_Detection/runs/detect/train/weights/best.pt"
model = YOLO(f"{path_weights}")

#Predict image
path_img = "/content/drive/MyDrive/Face_Detection/train/images/img_1_91_jpg.rf.813ed397b3d3888fc4117882085cb767.jpg"
results = model.predict(f"{path_img}")

"""### 1. Check Acc and Boudingbox"""

results = results[0]

for box in results.boxes:
  class_id = results.names[box.cls[0].item()]
  cords = box.xyxy[0].tolist()
  cords = [round(x) for x in cords]
  conf = round(box.conf[0].item(), 2)
  print("Object type:", class_id)
  print("Coordinates:", cords)
  print("Probability:", conf)
  print("---")

"""### 2. Show Image"""

from PIL import Image

Image.fromarray(results.plot()[:,:,::-1])

"""### Detection and Export by Video"""

!yolo detect predict model="/content/drive/MyDrive/Face_Detection/runs/detect/train/weights/best.pt" source="/content/drive/MyDrive/Face_Detection/test/3829249498855686133.mp4"